package ihm;

import DAO.UtilisateurDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Mara
 */
public class FenetreInscription extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreInscription.class.getName());

    /**
     * Creates new form FenetreInscription
     */
    public FenetreInscription() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordFieldMotDePasse = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordFieldConfirmation = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPrenom = new javax.swing.JTextField();
        jButtonInscrire = new javax.swing.JButton();
        jButtonRetour = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inscription Étudiant");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Créer un compte étudiant");

        jLabel2.setText("Login");

        jLabel3.setText("Mot de passe");

        jLabel4.setText("Confirmer mot de passe");

        jLabel5.setText("Nom");

        jLabel6.setText("Prénom");

        jButtonInscrire.setText("S'inscrire");
        jButtonInscrire.addActionListener(this::jButtonInscrireActionPerformed);

        jButtonRetour.setText("Retour");
        jButtonRetour.addActionListener(this::jButtonRetourActionPerformed);

        jLabelMessage.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldLogin)
                            .addComponent(jLabel3)
                            .addComponent(jPasswordFieldMotDePasse)
                            .addComponent(jLabel4)
                            .addComponent(jPasswordFieldConfirmation)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldNom)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(jLabelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jButtonRetour)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonInscrire)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInscrire)
                    .addComponent(jButtonRetour))
                .addGap(18, 18, 18)
                .addComponent(jLabelMessage)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInscrireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInscrireActionPerformed
        // Get form values
        String login = jTextFieldLogin.getText().trim();
        String motDePasse = new String(jPasswordFieldMotDePasse.getPassword());
        String confirmation = new String(jPasswordFieldConfirmation.getPassword());
        String nom = jTextFieldNom.getText().trim();
        String prenom = jTextFieldPrenom.getText().trim();
        
        // Validation: All fields required
        if (login.isEmpty() || motDePasse.isEmpty() || confirmation.isEmpty() || 
            nom.isEmpty() || prenom.isEmpty()) {
            jLabelMessage.setText("Tous les champs sont obligatoires");
            return;
        }
        
        // Validation: Password confirmation match
        if (!motDePasse.equals(confirmation)) {
            jLabelMessage.setText("Les mots de passe ne correspondent pas");
            return;
        }
        
        // Validation: Username uniqueness
        UtilisateurDAO utilisateurDAO = new UtilisateurDAO();
        if (utilisateurDAO.usernameExiste(login)) {
            jLabelMessage.setText("Ce nom d'utilisateur existe déjà");
            return;
        }
        
        // Register student
        int userId = utilisateurDAO.inscrireEtudiant(login, motDePasse, nom, prenom);
        
        if (userId > 0) {
            // Success
            JOptionPane.showMessageDialog(
                this,
                "Inscription réussie! Vous pouvez maintenant vous connecter.",
                "Succès",
                JOptionPane.INFORMATION_MESSAGE
            );
            
            // Return to login
            new FenetreLogin().setVisible(true);
            this.dispose();
        } else {
            // Error
            JOptionPane.showMessageDialog(
                this,
                "Erreur lors de l'inscription. Veuillez réessayer.",
                "Erreur",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jButtonInscrireActionPerformed

    private void jButtonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourActionPerformed
        // Return to login window
        new FenetreLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRetourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreInscription().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInscrire;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JPasswordField jPasswordFieldConfirmation;
    private javax.swing.JPasswordField jPasswordFieldMotDePasse;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenom;
    // End of variables declaration//GEN-END:variables
}
