/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ihm;

import java.util.List;
import java.util.ArrayList;

import DAO.QuizDAO;
import metier.Quiz;
import metier.Question;
/**
 *
 * @author Mara
 */
public class FenetreQuiz extends javax.swing.JFrame {
    private static final double PERCENTAGE_MULTIPLIER = 100.0;
    
    private List<Question> questions;
    private int indexQuestion = 0;
    private String titreQuiz;
    private int score = 0;
    private int quizId = -1;

private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());

    /**
     * Creates new form FenetreQuiz
     */
 public FenetreQuiz() {
    initComponents();
}
public FenetreQuiz(String titreQuiz) {
    initComponents();
    this.titreQuiz = titreQuiz;

    labelQuizTitre.setText("Quiz : " + titreQuiz);
    chargerQuestions();
    afficherQuestion();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        labelQuizTitre = new javax.swing.JLabel();
        labelQuestion = new javax.swing.JLabel();
        radioA = new javax.swing.JRadioButton();
        radioB = new javax.swing.JRadioButton();
        radioC = new javax.swing.JRadioButton();
        radioD = new javax.swing.JRadioButton();
        btnSuivant = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quiz");

        jLabel1.setText("Quiz en cours");

        labelQuizTitre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelQuizTitre.setText("Quiz :  ");

        labelQuestion.setText("Question ici ");

        buttonGroup1.add(radioA);
        radioA.setText("Réponse A");

        buttonGroup1.add(radioB);
        radioB.setText("Réponse B");

        buttonGroup1.add(radioC);
        radioC.setText("Réponse C");

        buttonGroup1.add(radioD);
        radioD.setText("Réponse D");
        radioD.addActionListener(this::radioDActionPerformed);

        btnSuivant.setText("Suivant");
        btnSuivant.addActionListener(this::btnSuivantActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSuivant)
                    .addComponent(radioD)
                    .addComponent(radioB)
                    .addComponent(radioA)
                    .addComponent(labelQuestion)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelQuizTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioC))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelQuizTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelQuestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSuivant)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void chargerQuestions() {
    QuizDAO quizDAO = new QuizDAO();
    Quiz quizTrouve = null;

    for (Quiz q : quizDAO.findAll()) {
        if (q.getTitre().equals(titreQuiz)) {
            quizTrouve = q;
            break;
        }
    }

    if (quizTrouve != null) {
        questions = quizTrouve.getQuestions();
        quizId = quizTrouve.getId();
    } else {
        questions = new java.util.ArrayList<>();
    }

    indexQuestion = 0;
    score = 0;
}


private void afficherQuestion() {
    if (questions == null || questions.isEmpty()) {
        labelQuestion.setText("Aucune question disponible pour ce quiz.");
        radioA.setEnabled(false);
        radioB.setEnabled(false);
        radioC.setEnabled(false);
        radioD.setEnabled(false);
        return;
    }

    if (indexQuestion >= questions.size()) {
        labelQuestion.setText("Quiz terminé.");
        radioA.setEnabled(false);
        radioB.setEnabled(false);
        radioC.setEnabled(false);
        radioD.setEnabled(false);
        return;
    }

Question q = questions.get(indexQuestion);

labelQuestion.setText(q.getEnonce());

List<String> choix = q.getChoix();

radioA.setText(choix.get(0));
radioB.setText(choix.get(1));
radioC.setText(choix.get(2));
radioD.setText(choix.get(3));


    buttonGroup1.clearSelection();
}

    private void radioDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioDActionPerformed

    private void btnSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivantActionPerformed
        // Check if an answer is selected
        if (buttonGroup1.getSelection() != null) {
            // Determine which radio button is selected
            int selectedAnswer = -1;
            if (radioA.isSelected()) selectedAnswer = 0;
            else if (radioB.isSelected()) selectedAnswer = 1;
            else if (radioC.isSelected()) selectedAnswer = 2;
            else if (radioD.isSelected()) selectedAnswer = 3;

            // Check if the answer is correct
            if (selectedAnswer != -1 && indexQuestion < questions.size()) {
                Question currentQuestion = questions.get(indexQuestion);
                if (selectedAnswer == currentQuestion.getBonneReponse()) {
                    score++;
                }
            }
        }

        indexQuestion++;
        
        if (indexQuestion >= questions.size()) {
            // Quiz finished - show results
            afficherResultats();
        } else {
            afficherQuestion();
        }
    }//GEN-LAST:event_btnSuivantActionPerformed

    private void afficherResultats() {
        int totalQuestions = questions.size();
        double pourcentage = totalQuestions > 0 ? (score * PERCENTAGE_MULTIPLIER / totalQuestions) : 0;
        
        String message = String.format(
            "Quiz terminé!\n\nScore: %d/%d (%.1f%%)",
            score, totalQuestions, pourcentage
        );
        
        javax.swing.JOptionPane.showMessageDialog(
            this,
            message,
            "Résultats du Quiz",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
        
        // Note: Saving attempt would require user context
        // For now, we just show the results
        // A proper implementation would save using TentativeDAO:
        // TentativeDAO tentativeDAO = new TentativeDAO();
        // tentativeDAO.save(new Tentative(currentUser, currentQuiz, score));
        
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuivant;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelQuestion;
    private javax.swing.JLabel labelQuizTitre;
    private javax.swing.JRadioButton radioA;
    private javax.swing.JRadioButton radioB;
    private javax.swing.JRadioButton radioC;
    private javax.swing.JRadioButton radioD;
    // End of variables declaration//GEN-END:variables
}
