package ihm;

import DAO.UtilisateurDAO;
import metier.Utilisateur;
import metier.RoleUtilisateur;

/**
 *
 * @author Mara
 */
public class FenetreLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreLogin.class.getName());

    /**
     * Creates new form FenetreLogin
     */
    public FenetreLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordFieldMotDePasse = new javax.swing.JPasswordField();
        jButtonSeConnecter = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();
        jButtonCreerCompte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Authentification");
        setResizable(false);

        jLabel1.setText("Login");

        jTextFieldLogin.setToolTipText("");

        jLabel2.setText("Mot de passe");

        jButtonSeConnecter.setText("Se connecter");
        jButtonSeConnecter.addActionListener(this::jButtonSeConnecterActionPerformed);

        jLabelMessage.setForeground(new java.awt.Color(255, 51, 51));

        jButtonCreerCompte.setText("Créer un compte");
        jButtonCreerCompte.addActionListener(this::jButtonCreerCompteActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelMessage))
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(jPasswordFieldMotDePasse)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jButtonSeConnecter))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jButtonCreerCompte)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSeConnecter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCreerCompte)
                .addGap(24, 24, 24)
                .addComponent(jLabelMessage)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSeConnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeConnecterActionPerformed
        String login = jTextFieldLogin.getText();
    String motDePasse = new String(jPasswordFieldMotDePasse.getPassword());

    if (login.isEmpty() || motDePasse.isEmpty()) {
        jLabelMessage.setText("Veuillez remplir tous les champs");
        return;
    }

    UtilisateurDAO utilisateurDAO = new UtilisateurDAO();
    Utilisateur utilisateur = utilisateurDAO.authentifier(login, motDePasse);

    // ❌ Authentication failed
    if (utilisateur == null) {
        jLabelMessage.setText("Login ou mot de passe incorrect");
        return;
    }

    // ✅ Authentication success
    jLabelMessage.setText(
        "Bienvenue " + utilisateur.getLogin() +
        " (" + utilisateur.getRole() + ")"
    );

    // 🎯 Role-based navigation
    if (utilisateur.getRole() == RoleUtilisateur.ETUDIANT) {
        new FenetreEtudiant(utilisateur).setVisible(true);

    } else if (utilisateur.getRole() == RoleUtilisateur.ENSEIGNANT) {
        new FenetreEnseignant().setVisible(true);
    }

    // Close login window
    this.dispose();
    }//GEN-LAST:event_jButtonSeConnecterActionPerformed

    private void jButtonCreerCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreerCompteActionPerformed
        // Open registration window
        new FenetreInscription().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCreerCompteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreerCompte;
    private javax.swing.JButton jButtonSeConnecter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JPasswordField jPasswordFieldMotDePasse;
    private javax.swing.JTextField jTextFieldLogin;
    // End of variables declaration//GEN-END:variables
}
