/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ihm;

import java.util.List;
import java.util.ArrayList;

import DAO.QuizDAO;
import DAO.TentativeDAO;
import metier.Quiz;
import metier.Question;
import metier.Utilisateur;
/**
 *
 * @author Mara
 */
public class FenetreQuiz extends javax.swing.JFrame {
    private static final double PERCENTAGE_MULTIPLIER = 100.0;
    private static final int TIMER_SECONDS_PER_QUESTION = 30; // 30 seconds per question
    private static final int WARNING_THRESHOLD_SECONDS = 30; // Show warning when 30 seconds remain in total
    
    private List<Question> questions;
    private int indexQuestion = 0;
    private String titreQuiz;
    private int score = 0;
    private int quizId = -1;
    private Utilisateur utilisateurConnecte;
    private int[] reponses; // Store selected answers for each question (-1 = not answered)
    
    // Timer related fields
    private javax.swing.Timer timer;
    private int tempsRestantSecondes;
    private int tempsTotalQuiz;
    private boolean warningShown = false;

private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());

    /**
     * Creates new form FenetreQuiz
     */
 public FenetreQuiz() {
    initComponents();
}
public FenetreQuiz(String titreQuiz) {
    this(titreQuiz, null);
}
public FenetreQuiz(String titreQuiz, Utilisateur utilisateur) {
    this.titreQuiz = titreQuiz;
    this.utilisateurConnecte = utilisateur;
    initComponents();

    labelQuizTitre.setText("Quiz : " + titreQuiz);
    chargerQuestions();
    reponses = new int[questions.size()];
    java.util.Arrays.fill(reponses, -1); // -1 means not answered
    
    // Initialize timer
    tempsTotalQuiz = questions.size() * TIMER_SECONDS_PER_QUESTION;
    tempsRestantSecondes = tempsTotalQuiz;
    
    afficherQuestion();
    demarrerTimer();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        labelQuizTitre = new javax.swing.JLabel();
        labelQuestion = new javax.swing.JLabel();
        radioA = new javax.swing.JRadioButton();
        radioB = new javax.swing.JRadioButton();
        radioC = new javax.swing.JRadioButton();
        radioD = new javax.swing.JRadioButton();
        btnPrecedent = new javax.swing.JButton();
        btnSuivant = new javax.swing.JButton();
        labelTempsRestant = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quiz");

        jLabel1.setText("Quiz en cours");

        labelQuizTitre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelQuizTitre.setText("Quiz :  ");
        
        labelTempsRestant.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTempsRestant.setForeground(new java.awt.Color(0, 102, 204));
        labelTempsRestant.setText("Temps restant: 00:00");

        labelQuestion.setText("Question ici ");

        buttonGroup1.add(radioA);
        radioA.setText("Réponse A");

        buttonGroup1.add(radioB);
        radioB.setText("Réponse B");

        buttonGroup1.add(radioC);
        radioC.setText("Réponse C");

        buttonGroup1.add(radioD);
        radioD.setText("Réponse D");
        radioD.addActionListener(this::radioDActionPerformed);

        btnPrecedent.setText("Précédent");
        btnPrecedent.setEnabled(false);
        btnPrecedent.addActionListener(this::btnPrecedentActionPerformed);

        btnSuivant.setText("Suivant");
        btnSuivant.addActionListener(this::btnSuivantActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrecedent)
                        .addGap(18, 18, 18)
                        .addComponent(btnSuivant))
                    .addComponent(radioD)
                    .addComponent(radioB)
                    .addComponent(radioA)
                    .addComponent(labelQuestion)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelQuizTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioC)
                    .addComponent(labelTempsRestant))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelQuizTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTempsRestant)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelQuestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrecedent)
                    .addComponent(btnSuivant))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void chargerQuestions() {
    QuizDAO quizDAO = new QuizDAO();
    Quiz quizTrouve = null;

    for (Quiz q : quizDAO.recupererListQuiz()) {
        if (q.getTitre().equals(titreQuiz)) {
            quizTrouve = q;
            break;
        }
    }

    if (quizTrouve != null) {
        questions = quizTrouve.getQuestions();
        quizId = quizTrouve.getId();
    } else {
        questions = new java.util.ArrayList<>();
    }

    indexQuestion = 0;
    score = 0;
}


private void afficherQuestion() {
    if (questions == null || questions.isEmpty()) {
        labelQuestion.setText("Aucune question disponible pour ce quiz.");
        radioA.setEnabled(false);
        radioB.setEnabled(false);
        radioC.setEnabled(false);
        radioD.setEnabled(false);
        return;
    }

    if (indexQuestion >= questions.size()) {
        labelQuestion.setText("Quiz terminé.");
        radioA.setEnabled(false);
        radioB.setEnabled(false);
        radioC.setEnabled(false);
        radioD.setEnabled(false);
        return;
    }

Question q = questions.get(indexQuestion);

labelQuestion.setText(q.getEnonce());

List<String> choix = q.getChoix();

radioA.setText(choix.get(0));
radioB.setText(choix.get(1));
radioC.setText(choix.get(2));
radioD.setText(choix.get(3));


    buttonGroup1.clearSelection();
    
    // Restore previously selected answer if exists
    if (reponses != null && indexQuestion >= 0 && indexQuestion < reponses.length && reponses[indexQuestion] != -1) {
        switch (reponses[indexQuestion]) {
            case 0: radioA.setSelected(true); break;
            case 1: radioB.setSelected(true); break;
            case 2: radioC.setSelected(true); break;
            case 3: radioD.setSelected(true); break;
        }
    }
    
    mettreAJourBoutons();
}

    private void radioDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDActionPerformed
        
    }//GEN-LAST:event_radioDActionPerformed

    private void btnSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivantActionPerformed
        // Save current answer
        sauvegarderReponse();
        
        if (indexQuestion >= questions.size() - 1) {
            // Last question - show confirmation dialog
            int confirmation = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Voulez-vous terminer le quiz ?",
                "Confirmation",
                javax.swing.JOptionPane.YES_NO_OPTION
            );
            
            if (confirmation == javax.swing.JOptionPane.YES_OPTION) {
                calculerScore();
                afficherResultats();
            }
        } else {
            indexQuestion++;
            afficherQuestion();
        }
    }//GEN-LAST:event_btnSuivantActionPerformed

    private void btnPrecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecedentActionPerformed
        // Save current answer before going back
        sauvegarderReponse();
        
        indexQuestion--;
        afficherQuestion();
    }//GEN-LAST:event_btnPrecedentActionPerformed
    
    private void sauvegarderReponse() {
        if (indexQuestion >= 0 && indexQuestion < questions.size() && reponses != null && indexQuestion < reponses.length) {
            if (radioA.isSelected()) reponses[indexQuestion] = 0;
            else if (radioB.isSelected()) reponses[indexQuestion] = 1;
            else if (radioC.isSelected()) reponses[indexQuestion] = 2;
            else if (radioD.isSelected()) reponses[indexQuestion] = 3;
            else reponses[indexQuestion] = -1;
        }
    }
    
    private void mettreAJourBoutons() {
        // Disable "Précédent" on first question
        btnPrecedent.setEnabled(indexQuestion > 0);
        
        // Change "Suivant" to "Terminer" on last question
        if (indexQuestion >= questions.size() - 1) {
            btnSuivant.setText("Terminer");
        } else {
            btnSuivant.setText("Suivant");
        }
    }
    
    private void calculerScore() {
        score = 0;
        for (int i = 0; i < questions.size(); i++) {
            if (reponses[i] == questions.get(i).getBonneReponse()) {
                score++;
            }
        }
    }

    private void afficherResultats() {
        // Stop timer when showing results
        arreterTimer();
        
        int totalQuestions = questions.size();
        double pourcentage = totalQuestions > 0 ? (score * PERCENTAGE_MULTIPLIER / totalQuestions) : 0;
        
        String message = String.format(
            "Quiz terminé!\n\nScore: %d/%d (%.1f%%)",
            score, totalQuestions, pourcentage
        );
        
        javax.swing.JOptionPane.showMessageDialog(
            this,
            message,
            "Résultats du Quiz",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
        
        // Save attempt to database
        if (utilisateurConnecte != null && quizId > 0) {
            TentativeDAO tentativeDAO = new TentativeDAO();
            tentativeDAO.ajouterTentative(utilisateurConnecte.getId(), quizId, score);
        }
        
        this.dispose();
    }

    /**
     * Start the countdown timer for the quiz
     */
    private void demarrerTimer() {
        // Create a timer that fires every second (1000 ms)
        timer = new javax.swing.Timer(1000, e -> {
            tempsRestantSecondes--;
            mettreAJourAffichageTimer();
            
            // Show warning when 30 seconds remain
            if (tempsRestantSecondes == WARNING_THRESHOLD_SECONDS && !warningShown) {
                warningShown = true;
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Attention ! Il vous reste 30 secondes pour terminer le quiz !",
                    "Avertissement",
                    javax.swing.JOptionPane.WARNING_MESSAGE
                );
            }
            
            // Auto-submit when time runs out
            if (tempsRestantSecondes <= 0) {
                arreterTimer();
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Temps écoulé ! Le quiz est terminé automatiquement.",
                    "Fin du temps",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
                );
                calculerScore();
                afficherResultats();
            }
        });
        
        mettreAJourAffichageTimer();
        timer.start();
    }
    
    /**
     * Stop the timer
     */
    private void arreterTimer() {
        if (timer != null && timer.isRunning()) {
            timer.stop();
        }
    }
    
    /**
     * Update the timer display label
     */
    private void mettreAJourAffichageTimer() {
        int minutes = tempsRestantSecondes / 60;
        int secondes = tempsRestantSecondes % 60;
        String texteTimer = String.format("Temps restant: %02d:%02d", minutes, secondes);
        labelTempsRestant.setText(texteTimer);
        
        // Change color to red when less than or equal to 30 seconds remain
        if (tempsRestantSecondes <= WARNING_THRESHOLD_SECONDS) {
            labelTempsRestant.setForeground(new java.awt.Color(255, 0, 0));
        } else {
            labelTempsRestant.setForeground(new java.awt.Color(0, 102, 204));
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrecedent;
    private javax.swing.JButton btnSuivant;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelQuestion;
    private javax.swing.JLabel labelQuizTitre;
    private javax.swing.JLabel labelTempsRestant;
    private javax.swing.JRadioButton radioA;
    private javax.swing.JRadioButton radioB;
    private javax.swing.JRadioButton radioC;
    private javax.swing.JRadioButton radioD;
    // End of variables declaration//GEN-END:variables
}
