/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ihm;
import DAO.QuizDAO;
import metier.Quiz;
import java.util.List;

/**
 *
 * @author Mara
 */
public class FenetreEtudiant extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreEtudiant.class.getName());

    /**
     * Creates new form FenetreEtudiant
     */
    public FenetreEtudiant() {
        initComponents();
        chargerQuizzes();
    }
private void chargerQuizzes() {
    comboQuiz.removeAllItems();

    QuizDAO quizDAO = new QuizDAO();
    List<Quiz> quizzes = quizDAO.recupererListQuiz();

    for (Quiz quiz : quizzes) {
        comboQuiz.addItem(quiz.getTitre());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonCommencerQuiz = new javax.swing.JButton();
        jButtonDeconnexion = new javax.swing.JButton();
        comboQuiz = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Espace Étudiant");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenue dans le Quiz");

        jButtonCommencerQuiz.setText("Commencer le Quiz");
        jButtonCommencerQuiz.addActionListener(this::jButtonCommencerQuizActionPerformed);

        jButtonDeconnexion.setText("Déconnexion");
        jButtonDeconnexion.addActionListener(this::jButtonDeconnexionActionPerformed);

        comboQuiz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboQuiz.addActionListener(this::comboQuizActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jButtonCommencerQuiz))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDeconnexion)
                            .addComponent(comboQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButtonCommencerQuiz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jButtonDeconnexion)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCommencerQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCommencerQuizActionPerformed
         String titreQuiz = comboQuiz.getSelectedItem().toString();

    FenetreQuiz fenetreQuiz = new FenetreQuiz(titreQuiz);
    fenetreQuiz.setVisible(true);

    this.dispose();

    }//GEN-LAST:event_jButtonCommencerQuizActionPerformed

    private void jButtonDeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeconnexionActionPerformed
        new FenetreLogin().setVisible(true);
this.dispose();

    }//GEN-LAST:event_jButtonDeconnexionActionPerformed

    private void comboQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboQuizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboQuizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreEtudiant().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboQuiz;
    private javax.swing.JButton jButtonCommencerQuiz;
    private javax.swing.JButton jButtonDeconnexion;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
