/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ihm;

/**
 *
 * @author Mara
 */
public class FenetreEnseignant extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreEnseignant.class.getName());

    /**
     * Creates new form FenetreEnseignant
     */
    public FenetreEnseignant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonCreerQuiz = new javax.swing.JButton();
        jButtonVoirQuiz = new javax.swing.JButton();
        jButtonResultats = new javax.swing.JButton();
        jButtonDeconnexion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Espace Enseignant");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Gestion des Quiz");
        jLabel1.setToolTipText("");

        jButtonCreerQuiz.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonCreerQuiz.setText("Créer un Quiz");
        jButtonCreerQuiz.addActionListener(this::jButtonCreerQuizActionPerformed);

        jButtonVoirQuiz.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonVoirQuiz.setText("Voir les Quiz");
        jButtonVoirQuiz.addActionListener(this::jButtonVoirQuizActionPerformed);

        jButtonResultats.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonResultats.setText("Résultats Étudiants");
        jButtonResultats.addActionListener(this::jButtonResultatsActionPerformed);

        jButtonDeconnexion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonDeconnexion.setText("Déconnexion");
        jButtonDeconnexion.addActionListener(this::jButtonDeconnexionActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCreerQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonVoirQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonResultats, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonDeconnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCreerQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVoirQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonResultats, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButtonDeconnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeconnexionActionPerformed
        new FenetreLogin().setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButtonDeconnexionActionPerformed

    private void jButtonCreerQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreerQuizActionPerformed
        new FenetreCreationQuiz().setVisible(true);

    }//GEN-LAST:event_jButtonCreerQuizActionPerformed

    private void jButtonVoirQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoirQuizActionPerformed
        new FenetreListeQuiz().setVisible(true);

    }//GEN-LAST:event_jButtonVoirQuizActionPerformed

    private void jButtonResultatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResultatsActionPerformed
        new FenetreResultats().setVisible(true);

    }//GEN-LAST:event_jButtonResultatsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreEnseignant().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreerQuiz;
    private javax.swing.JButton jButtonDeconnexion;
    private javax.swing.JButton jButtonResultats;
    private javax.swing.JButton jButtonVoirQuiz;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
