/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ihm;
import DAO.QuizDAO;
import metier.Quiz;
import metier.Utilisateur;
import java.util.List;

/**
 *
 * @author Mara
 */
public class FenetreEtudiant extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreEtudiant.class.getName());
    private Utilisateur utilisateurConnecte;

    /**
     * Creates new form FenetreEtudiant
     */
    public FenetreEtudiant() {
        initComponents();
        chargerQuizzes();
    }

    public FenetreEtudiant(Utilisateur utilisateur) {
        this.utilisateurConnecte = utilisateur;
        initComponents();
        chargerQuizzes();
    }
private void chargerQuizzes() {
    comboQuiz.removeAllItems();

    QuizDAO quizDAO = new QuizDAO();
    List<Quiz> quizzes = quizDAO.recupererListQuiz();

    for (Quiz quiz : quizzes) {
        comboQuiz.addItem(quiz.getTitre());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonCommencerQuiz = new javax.swing.JButton();
        jButtonMesResultats = new javax.swing.JButton();
        jButtonDeconnexion = new javax.swing.JButton();
        comboQuiz = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Espace Étudiant");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenue dans le Quiz");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Sélectionnez un quiz :");

        jButtonCommencerQuiz.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonCommencerQuiz.setText("Commencer le Quiz");
        jButtonCommencerQuiz.addActionListener(this::jButtonCommencerQuizActionPerformed);

        jButtonMesResultats.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonMesResultats.setText("Historique des Résultats");
        jButtonMesResultats.setBackground(new java.awt.Color(51, 153, 255));
        jButtonMesResultats.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMesResultats.setOpaque(true);
        jButtonMesResultats.addActionListener(this::jButtonMesResultatsActionPerformed);

        jButtonDeconnexion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonDeconnexion.setText("Déconnexion");
        jButtonDeconnexion.addActionListener(this::jButtonDeconnexionActionPerformed);

        comboQuiz.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboQuiz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboQuiz.addActionListener(this::comboQuizActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(comboQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCommencerQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMesResultats, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeconnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addComponent(comboQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButtonCommencerQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jButtonMesResultats, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButtonDeconnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCommencerQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCommencerQuizActionPerformed
         String titreQuiz = comboQuiz.getSelectedItem().toString();

    FenetreQuiz fenetreQuiz = new FenetreQuiz(titreQuiz, utilisateurConnecte);
    fenetreQuiz.setVisible(true);

    this.dispose();

    }//GEN-LAST:event_jButtonCommencerQuizActionPerformed

    private void jButtonDeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeconnexionActionPerformed
        new FenetreLogin().setVisible(true);
this.dispose();

    }//GEN-LAST:event_jButtonDeconnexionActionPerformed

    private void comboQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboQuizActionPerformed
        
    }//GEN-LAST:event_comboQuizActionPerformed

    private void jButtonMesResultatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesResultatsActionPerformed
        new FenetreMesResultats(utilisateurConnecte).setVisible(true);
    }//GEN-LAST:event_jButtonMesResultatsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreEtudiant().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboQuiz;
    private javax.swing.JButton jButtonCommencerQuiz;
    private javax.swing.JButton jButtonDeconnexion;
    private javax.swing.JButton jButtonMesResultats;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
