/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ihm;

import DAO.QuizDAO;
import metier.Quiz;
import model.QuizTableModel;
import java.util.List;

/**
 *
 * @author Mara
 */
public class FenetreListeQuiz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreListeQuiz.class.getName());
    private QuizTableModel quizTableModel;

    /**
     * Creates new form FenetreListeQuiz
     */
    public FenetreListeQuiz() {
        initComponents();
        quizTableModel = new QuizTableModel();
        tableQuizzes.setModel(quizTableModel);
        chargerQuizzes();
    }

    private void chargerQuizzes() {
        QuizDAO quizDAO = new QuizDAO();
        List<Quiz> quizzes = quizDAO.recupererListQuiz();
        quizTableModel.setItems(quizzes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableQuizzes = new javax.swing.JTable();
        btnSupprimer = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnAjouterQuestions = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Liste des Quiz");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Liste des Quiz");

        tableQuizzes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titre", "Nombre de Questions"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableQuizzes.getSelectionModel().addListSelectionListener(this::tableSelectionChanged);
        jScrollPane1.setViewportView(tableQuizzes);

        btnSupprimer.setText("Supprimer");
        btnSupprimer.setEnabled(false);
        btnSupprimer.addActionListener(this::btnSupprimerActionPerformed);

        btnModifier.setText("Modifier");
        btnModifier.setEnabled(false);
        btnModifier.addActionListener(this::btnModifierActionPerformed);

        btnAjouterQuestions.setText("Ajouter Questions");
        btnAjouterQuestions.setEnabled(false);
        btnAjouterQuestions.addActionListener(this::btnAjouterQuestionsActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAjouterQuestions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSupprimer)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSupprimer)
                    .addComponent(btnModifier)
                    .addComponent(btnAjouterQuestions))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableSelectionChanged(javax.swing.event.ListSelectionEvent evt) {
        boolean hasSelection = tableQuizzes.getSelectedRow() != -1;
        btnSupprimer.setEnabled(hasSelection);
        btnModifier.setEnabled(hasSelection);
        btnAjouterQuestions.setEnabled(hasSelection);
    }

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        int selectedRow = tableQuizzes.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }

        Quiz quizSelectionne = quizTableModel.getQuizAt(selectedRow);
        
        int confirmation = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Êtes-vous sûr de vouloir supprimer le quiz \"" + quizSelectionne.getTitre() + "\" ?",
            "Confirmation de suppression",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE
        );
        
        if (confirmation == javax.swing.JOptionPane.YES_OPTION) {
            QuizDAO quizDAO = new QuizDAO();
            int resultat = quizDAO.supprimerQuiz(quizSelectionne.getId());
            
            if (resultat > 0) {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Quiz supprimé avec succès!",
                    "Succès",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
                );
                chargerQuizzes();
            } else {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Erreur lors de la suppression du quiz",
                    "Erreur",
                    javax.swing.JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        int selectedRow = tableQuizzes.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }

        Quiz quizSelectionne = quizTableModel.getQuizAt(selectedRow);
        
        String nouveauTitre = javax.swing.JOptionPane.showInputDialog(
            this,
            "Nouveau titre du quiz:",
            quizSelectionne.getTitre()
        );
        
        if (nouveauTitre != null && !nouveauTitre.trim().isEmpty()) {
            QuizDAO quizDAO = new QuizDAO();
            int resultat = quizDAO.modifierQuiz(quizSelectionne.getId(), nouveauTitre.trim());
            
            if (resultat > 0) {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Quiz modifié avec succès!",
                    "Succès",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
                );
                chargerQuizzes();
            } else {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Erreur lors de la modification du quiz",
                    "Erreur",
                    javax.swing.JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnAjouterQuestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterQuestionsActionPerformed
        int selectedRow = tableQuizzes.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }

        Quiz quizSelectionne = quizTableModel.getQuizAt(selectedRow);
        
        // Show dialog to add a question
        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridLayout(0, 1, 5, 5));
        
        javax.swing.JTextField txtEnonce = new javax.swing.JTextField(30);
        javax.swing.JTextField txtChoixA = new javax.swing.JTextField(30);
        javax.swing.JTextField txtChoixB = new javax.swing.JTextField(30);
        javax.swing.JTextField txtChoixC = new javax.swing.JTextField(30);
        javax.swing.JTextField txtChoixD = new javax.swing.JTextField(30);
        
        String[] reponseOptions = {"A", "B", "C", "D"};
        javax.swing.JComboBox<String> cmbBonneReponse = new javax.swing.JComboBox<>(reponseOptions);
        
        panel.add(new javax.swing.JLabel("Énoncé de la question:"));
        panel.add(txtEnonce);
        panel.add(new javax.swing.JLabel("Choix A:"));
        panel.add(txtChoixA);
        panel.add(new javax.swing.JLabel("Choix B:"));
        panel.add(txtChoixB);
        panel.add(new javax.swing.JLabel("Choix C:"));
        panel.add(txtChoixC);
        panel.add(new javax.swing.JLabel("Choix D:"));
        panel.add(txtChoixD);
        panel.add(new javax.swing.JLabel("Bonne réponse:"));
        panel.add(cmbBonneReponse);
        
        int result = javax.swing.JOptionPane.showConfirmDialog(
            this,
            panel,
            "Ajouter une question au quiz \"" + quizSelectionne.getTitre() + "\"",
            javax.swing.JOptionPane.OK_CANCEL_OPTION,
            javax.swing.JOptionPane.PLAIN_MESSAGE
        );
        
        if (result == javax.swing.JOptionPane.OK_OPTION) {
            String enonce = txtEnonce.getText().trim();
            String choixA = txtChoixA.getText().trim();
            String choixB = txtChoixB.getText().trim();
            String choixC = txtChoixC.getText().trim();
            String choixD = txtChoixD.getText().trim();
            
            if (enonce.isEmpty() || choixA.isEmpty() || choixB.isEmpty() || 
                choixC.isEmpty() || choixD.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Tous les champs doivent être remplis!",
                    "Erreur",
                    javax.swing.JOptionPane.ERROR_MESSAGE
                );
                return;
            }
            
            int bonneReponse = cmbBonneReponse.getSelectedIndex();
            
            DAO.QuestionDAO questionDAO = new DAO.QuestionDAO();
            int resultatAjout = questionDAO.ajouterQuestion(
                enonce, choixA, choixB, choixC, choixD, bonneReponse, quizSelectionne.getId()
            );
            
            if (resultatAjout > 0) {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Question ajoutée avec succès!",
                    "Succès",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
                );
                chargerQuizzes(); // Refresh the table to show updated question count
            } else {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Erreur lors de l'ajout de la question",
                    "Erreur",
                    javax.swing.JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_btnAjouterQuestionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreListeQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterQuestions;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableQuizzes;
    // End of variables declaration//GEN-END:variables
}
